name: Test Action

on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: project

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=latest,name=iPhone 11']
    steps:
      - id: testCheckout
        uses: actions/checkout@master
      - id: testStep
        name: Test with ${{ matrix.destination }}
        run: xcodebuild clean test -project "${PROJECT}.xcodeproj" -scheme "${PROJECT}" -destination "${{ matrix.destination }}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
          PROJECT: "Tembici Movies"

  build:
    name: Build Project
    runs-on: macos-latest
    needs: [test]
    steps:
      - id: buildCheckout
        uses: actions/checkout@master
      - id: buildStep
        name: Build
        run: xcodebuild clean build -project "${PROJECT}.xcodeproj" -scheme "${PROJECT}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO CODE_SIGNING_ALLOWED=NO 
        env:
          PROJECT: "Tembici Movies"
